server:
  port : 8081
spring:
  datasource:
    url: jdbc:h2:mem:prices
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: true
    spring.h2.console.settings.web-allow-others: false

